### ISSUE TITLE
Web server not starting

### ISSUE THREAD

**Issue by njordhov** [loganpowell/shadow-proto-starter#1]
In [shadow-cljs.edn](https://github.com/loganpowell/shadow-proto-starter/blob/master/shadow-cljs.edn) `:devtools` is a child of `:modules` but should rather be a sibling. As a consequence, the example fails to start an http server.

**Comment by loganpowell** [comment]
I would happily take a PR for these issues if you have them handy on your local. I am currently under water with a number of other projects and a new computer...
