### ISSUE TITLE
Consider lifecycle hooks

### ISSUE THREAD

**Issue by njordhov** [loganpowell/shadow-proto-starter#2]
The `:devtools` in [shadow-cljs.edn](https://github.com/loganpowell/shadow-proto-starter/blob/master/shadow-cljs.edn) currently declares `:before-load app.core/stop`. Consider replacing through `defn ^:dev/before-load stop` in [src/app/core.cljs](https://github.com/loganpowell/shadow-proto-starter/blob/master/src/app/core.cljs). Ditto for `:after-load` as documented in the [Shadow Users Guide](https://shadow-cljs.github.io/docs/UsersGuide.html#_lifecycle_hooks).

**Comment by loganpowell** [comment]
Thank you @TerjeNorderhaug I will do this when I get the time...
